Repository Y-edu/Y-edu-backend, pull requests merged in 2025-04, with the labels that each got.

#94 feat : 매칭 테이블 enum값 수정
  src/main/java/com/yedu/backend/domain/matching/domain/entity/constant/MatchingStatus.java
  src/main/resources/db/migration/V3_202504031746__alter_modify_status.sql
Labels: 📜 Docs, ✨ Feature

#95 feat : 상담 결과 저장 테이블 추가
  src/main/java/com/yedu/backend/domain/matching/domain/entity/ClassManagement.java
  src/main/java/com/yedu/backend/domain/matching/domain/entity/ClassSchedule.java
  src/main/java/com/yedu/backend/domain/matching/domain/vo/ClassTime.java
  src/main/resources/db/migration/V3_202504031850__create_class_schedule.sql
Labels: ✨ Feature

#97 feat : 매칭 후반부 자동화 REST API
  src/main/java/com/yedu/backend/domain/matching/application/dto/req/ClassScheduleConfirmRequest.java
  src/main/java/com/yedu/backend/domain/matching/application/dto/req/ClassScheduleMatchingRequest.java
  src/main/java/com/yedu/backend/domain/matching/application/dto/req/ClassScheduleMatchingResponse.java
  src/main/java/com/yedu/backend/domain/matching/application/dto/req/ClassScheduleRefuseRequest.java
  src/main/java/com/yedu/backend/domain/matching/application/usecase/ClassScheduleMatchingUseCase.java
  src/main/java/com/yedu/backend/domain/matching/domain/entity/ClassManagement.java
  src/main/java/com/yedu/backend/domain/matching/domain/entity/ClassMatching.java
  src/main/java/com/yedu/backend/domain/matching/domain/repository/ClassManagementRepository.java
  src/main/java/com/yedu/backend/domain/matching/domain/service/ClassManagementCommandService.java
  src/main/java/com/yedu/backend/domain/matching/domain/service/ClassMatchingGetService.java
  src/main/java/com/yedu/backend/domain/matching/domain/vo/ClassTime.java
  src/main/java/com/yedu/backend/domain/matching/presentation/ClassMatchingScheduleController.java
  src/main/java/com/yedu/backend/global/exception/matching/ClassManagementNotFoundException.java
  src/main/java/com/yedu/backend/global/exception/matching/MatchingNotFoundException.java
  src/main/java/com/yedu/backend/global/exception/matching/constant/MatchingErrorCode.java
Labels: ✨ Feature

#98 refactor : 상담 신청 API 응답 필드 타입 수정
  src/main/java/com/yedu/backend/domain/matching/application/dto/req/ClassScheduleConfirmRequest.java
  src/main/java/com/yedu/backend/domain/matching/application/dto/req/ClassScheduleMatchingResponse.java
  src/main/java/com/yedu/backend/domain/matching/application/dto/req/ClassScheduleRefuseRequest.java
  src/main/java/com/yedu/backend/domain/matching/application/usecase/ClassScheduleMatchingUseCase.java
  src/main/java/com/yedu/backend/domain/matching/domain/service/ClassManagementCommandService.java
  src/main/java/com/yedu/backend/domain/matching/domain/service/ClassManagementKeyStorage.java
  src/main/java/com/yedu/backend/domain/matching/presentation/ClassMatchingScheduleController.java
Labels: 🛠️ Refactor

#101 feat : 상담 결과 조회 API 추가, 토큰 만료 로직 추가
  src/main/java/com/yedu/backend/domain/matching/application/dto/req/ClassScheduleRetrieveRequest.java
  src/main/java/com/yedu/backend/domain/matching/application/dto/req/ClassScheduleRetrieveResponse.java
  src/main/java/com/yedu/backend/domain/matching/application/usecase/ClassScheduleMatchingUseCase.java
  src/main/java/com/yedu/backend/domain/matching/domain/repository/ClassManagementRepository.java
  src/main/java/com/yedu/backend/domain/matching/domain/service/ClassManagementCommandService.java
  src/main/java/com/yedu/backend/domain/matching/domain/service/ClassManagementKeyStorage.java
  src/main/java/com/yedu/backend/domain/matching/domain/service/ClassManagementQueryService.java
  src/main/java/com/yedu/backend/domain/matching/domain/vo/ClassTime.java
  src/main/java/com/yedu/backend/domain/matching/presentation/ClassMatchingScheduleController.java
Labels: ✨ Feature

#102 feat : 알림톡 전송 step1
  src/main/java/com/yedu/backend/bizppurio/application/mapper/BizppurioMapper.java
  src/main/java/com/yedu/backend/bizppurio/application/usecase/BizppurioCheckStep.java
  src/main/java/com/yedu/backend/bizppurio/application/usecase/BizppurioParentsMessage.java
  src/main/java/com/yedu/backend/bizppurio/application/usecase/BizppurioSend.java
  src/main/java/com/yedu/backend/bizppurio/application/usecase/BizppurioTeacherMessage.java
  src/main/java/com/yedu/backend/bizppurio/presentation/BizppurioController.java
  src/main/java/com/yedu/backend/domain/matching/application/usecase/ClassScheduleMatchingUseCase.java
  src/main/java/com/yedu/backend/domain/matching/domain/service/ClassManagementCommandService.java
  src/main/java/com/yedu/backend/global/event/dto/MatchingConfirmTeacherEvent.java
  src/main/java/com/yedu/backend/global/event/dto/MatchingParentsEvent.java
  src/main/java/com/yedu/backend/global/event/dto/ParentsClassInfoEvent.java
  src/main/java/com/yedu/backend/global/event/dto/TeacherClassRemindEvent.java
  src/main/java/com/yedu/backend/global/event/dto/TeacherExchangeEvent.java
  src/main/java/com/yedu/backend/global/event/listener/BizppurioParentsMessageListener.java
  src/main/java/com/yedu/backend/global/event/listener/BizppurioTeacherMessageListener.java
  src/main/java/com/yedu/backend/global/event/mapper/EventMapper.java
  src/main/java/com/yedu/backend/global/event/publisher/BizppurioEventPublisher.java
Labels: ✨ Feature

#105 accept count 조건 수정
  src/main/java/com/yedu/backend/admin/application/mapper/AdminMapper.java
  src/main/java/com/yedu/backend/admin/application/usecase/AdminInfoUseCase.java
  src/main/java/com/yedu/backend/domain/matching/domain/entity/ClassMatching.java
Labels: 🛠️ Refactor

#106 refactor : 상담 시작시 매칭상태 validation 추가 & accept count 미적용된 부분 반영
  src/main/java/com/yedu/backend/admin/application/dto/res/AllApplicationResponse.java
  src/main/java/com/yedu/backend/admin/application/dto/res/ClassDetailsResponse.java
  src/main/java/com/yedu/backend/admin/application/dto/res/ScheduledClass.java
  src/main/java/com/yedu/backend/admin/application/mapper/AdminMapper.java
  src/main/java/com/yedu/backend/admin/application/usecase/AdminInfoUseCase.java
  src/main/java/com/yedu/backend/domain/matching/domain/entity/ClassMatching.java
  src/main/java/com/yedu/backend/domain/matching/domain/repository/ClassMatchingRepository.java
  src/main/java/com/yedu/backend/domain/matching/domain/service/ClassMatchingGetService.java
  src/main/java/com/yedu/backend/global/exception/matching/MatchingNotSendStatusException.java
  src/main/java/com/yedu/backend/global/exception/matching/constant/MatchingErrorCode.java
Labels: 🛠️ Refactor

#108 Hotfix : 알림톡 중단
  src/main/java/com/yedu/backend/admin/presentation/AdminTestController.java
  src/main/java/com/yedu/backend/domain/parents/application/usecase/ParentsManageUseCase.java
Labels: 🚨 Hotfix

#109 fix : 학부모 알림톡 중단
  src/main/java/com/yedu/backend/admin/presentation/AdminTestController.java
  src/main/java/com/yedu/backend/domain/parents/application/usecase/ParentsManageUseCase.java
  src/main/java/com/yedu/backend/global/event/publisher/BizppurioEventPublisher.java
Labels: 🐞BugFix

#112 feat : 웹훅 메시지 상세화
  api/src/main/java/com/yedu/backend/domain/matching/application/dto/req/ClassScheduleConfirmRequest.java
  api/src/main/java/com/yedu/backend/domain/matching/application/usecase/ClassScheduleMatchingUseCase.java
  api/src/main/java/com/yedu/backend/domain/matching/domain/entity/ClassMatching.java
  api/src/main/java/com/yedu/backend/domain/matching/domain/service/ClassManagementCommandService.java
  api/src/main/java/com/yedu/backend/domain/matching/domain/vo/ClassTime.java
  api/src/main/java/com/yedu/backend/global/discord/DiscordWebhookUseCase.java
  shared/discord-support/src/main/java/com/yedu/discord/support/DiscordMapper.java
  shared/discord-support/src/main/java/com/yedu/discord/support/DiscordWebClientProperties.java
  shared/discord-support/src/main/java/com/yedu/discord/support/DiscordWebClientTemplate.java
  shared/discord-support/src/main/java/com/yedu/discord/support/DiscordWebhookType.java
Labels: ✨ Feature

#114 feat : webclient retry 로직 추가
  api/src/main/java/com/yedu/backend/bizppurio/application/mapper/BizppurioMapper.java
  shared/discord-support/src/main/java/com/yedu/discord/support/DiscordWebClientProperties.java
  shared/discord-support/src/main/java/com/yedu/discord/support/DiscordWebClientTemplate.java
Labels: 🛠️ Refactor

#122 feat : application 설정파일 추가
  .github/workflows/CD-develop.yml
  .github/workflows/CD-prod.yml
  .github/workflows/CI-develop.yml
  .github/workflows/CI-prod.yml
  .gitignore
  Dockerfile
  api/src/main/resources/application.yml
Labels: 🛠️ Refactor

#125 fix : 모듈 이동 및 의존성 수정
  api/build.gradle.kts
  api/src/main/java/com/yedu/backend/global/bizppurio/BizppurioController.java
  shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/application/usecase/BizppurioCheckStep.java
  shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/config/BizppurioWebClientConfig.java
  shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/event/mapper/DiscordEventMapper.java
  shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/event/publisher/BizppurioModuleEventPublisher.java
Labels: 🐞BugFix, 🛠️ Refactor

#128 feat : timetable 관련 테이블 추가
  api/src/main/resources/db/migration/V4_202504161130__create_time_table.sql
Labels: ✨ Feature

#132 feat : tally 폼에서 과외 타임 테이블 저장하도록 수정
  api/src/main/java/com/yedu/backend/domain/parents/application/dto/req/ApplicationFormRequest.java
  api/src/main/java/com/yedu/backend/domain/parents/application/dto/res/ApplicationFormTimeTableResponse.java
  api/src/main/java/com/yedu/backend/domain/parents/application/mapper/ApplicationFormAvailableMapper.java
  api/src/main/java/com/yedu/backend/domain/parents/application/usecase/ParentsManageUseCase.java
  api/src/main/java/com/yedu/backend/domain/parents/domain/service/ApplicationFormAvailableCommandService.java
  api/src/main/java/com/yedu/backend/domain/parents/domain/vo/DayTime.java
  api/src/main/resources/db/migration/V4_202504172150__alter_matching_timetable_fk.sql
Labels: ✨ Feature

#133 feat : 선생님 과외 공지 알림톡 발송 조건 수정 (타임테이블 주 n회 겹치는 경우에만 발송)
  api/src/main/java/com/yedu/backend/domain/parents/application/mapper/ParentsMapper.java
  api/src/main/java/com/yedu/backend/domain/parents/application/usecase/ParentsManageUseCase.java
  api/src/main/java/com/yedu/backend/domain/teacher/application/usecase/TeacherInfoUseCase.java
  api/src/main/java/com/yedu/backend/domain/teacher/domain/aggregate/TeacherWithAvailable.java
  api/src/main/java/com/yedu/backend/domain/teacher/domain/entity/TeacherAvailable.java
  api/src/main/java/com/yedu/backend/domain/teacher/domain/repository/TeacherDslRepository.java
  api/src/main/java/com/yedu/backend/domain/teacher/domain/repository/TeacherDslRepositoryImpl.java
  api/src/main/java/com/yedu/backend/domain/teacher/domain/service/TeacherGetService.java
Labels: ✨ Feature

#138 refactor : code lint tool 추가
  build.gradle.kts
Labels: 🛠️ Refactor

#137 feat : 토큰기반으로 과외 추천 알림톡 발송시 한번에 선생님 정보 조회가능하도록 BFF API 추가
  api/src/main/java/com/yedu/backend/admin/application/dto/req/TeacherSearchRequest.java
  api/src/main/java/com/yedu/backend/admin/application/dto/res/AllAlarmTalkResponse.java
  api/src/main/java/com/yedu/backend/admin/application/dto/res/AllFilteringTeacher.java
  api/src/main/java/com/yedu/backend/admin/application/dto/res/ClassDetailsResponse.java
  api/src/main/java/com/yedu/backend/admin/application/mapper/AdminMapper.java
  api/src/main/java/com/yedu/backend/admin/application/usecase/AdminManageUseCase.java
  api/src/main/java/com/yedu/backend/admin/presentation/AdminController.java
  api/src/main/java/com/yedu/backend/domain/matching/application/dto/res/ClassMatchingForTeacherResponse.java
  api/src/main/java/com/yedu/backend/domain/matching/application/usecase/MatchingTimetableUseCase.java
  api/src/main/java/com/yedu/backend/domain/parents/application/dto/req/ApplicationFormRequest.java
  api/src/main/java/com/yedu/backend/domain/parents/domain/entity/ApplicationForm.java
  api/src/main/java/com/yedu/backend/domain/teacher/application/dto/res/TeacherAllInformationResponse.java
  api/src/main/java/com/yedu/backend/domain/teacher/application/usecase/TeacherBffInfoUseCase.java
  api/src/main/java/com/yedu/backend/domain/teacher/domain/repository/TeacherDslRepositoryImpl.java
  api/src/main/java/com/yedu/backend/domain/teacher/presentation/TeacherBffController.java
  api/src/main/java/com/yedu/backend/global/event/mapper/BizppurioEventMapper.java
  shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/application/mapper/BizppurioMapper.java
  shared/cache-support/build.gradle.kts
  shared/cache-support/src/main/java/com/yedu/cache/support/dto/MatchingTimeTableDto.java
  shared/cache-support/src/main/java/com/yedu/cache/support/storage/AbstractKeyStorage.java
  shared/cache-support/src/main/java/com/yedu/cache/support/storage/ClassManagementKeyStorage.java
  shared/cache-support/src/main/java/com/yedu/cache/support/storage/MatchingTimetableKeyStorage.java
  shared/common/src/main/java/com/yedu/common/event/bizppurio/RecommendTeacherEvent.java
  shared/common/src/main/java/com/yedu/common/type/ClassType.java
Labels: ✨ Feature

#139 fix : 선생님 과외 공지 API 응답 수정
  api/src/main/java/com/yedu/backend/domain/matching/application/dto/res/ClassMatchingForTeacherResponse.java
  api/src/main/java/com/yedu/backend/domain/matching/application/mapper/ClassMatchingMapper.java
  api/src/main/java/com/yedu/backend/domain/matching/application/usecase/ClassMatchingInfoUseCase.java
  api/src/main/java/com/yedu/backend/domain/parents/application/dto/req/ApplicationFormRequest.java
  api/src/main/java/com/yedu/backend/domain/parents/application/mapper/ParentsMapper.java
  api/src/main/java/com/yedu/backend/domain/parents/domain/entity/ApplicationForm.java
  api/src/main/java/com/yedu/backend/domain/parents/domain/vo/DayTime.java
Labels: 🐞BugFix

#146 Hotfix : 파일명 수정
  api/src/main/resources/db/migration/V4_202504221923__alter_classMatching_status_2.sql
Labels: 🚨 Hotfix

#148 feat : 선생님 가능 시간 변경 토큰용 API 개발
  api/src/main/java/com/yedu/backend/domain/teacher/application/dto/req/AvailableChangeTokenRequest.java
  api/src/main/java/com/yedu/backend/domain/teacher/application/mapper/TeacherMapper.java
  api/src/main/java/com/yedu/backend/domain/teacher/application/usecase/TeacherManageUseCase.java
  api/src/main/java/com/yedu/backend/domain/teacher/presentation/TeacherController.java
Labels: ✨ Feature

#150 fix : JPA 매핑 버그 수정
  api/src/main/java/com/yedu/backend/domain/matching/domain/entity/MatchingTimetable.java
  shared/discord-support/src/main/java/com/yedu/discord/support/DiscordWebhookUseCase.java
  shared/discord-support/src/main/java/com/yedu/discord/support/listener/DiscordEventListener.java
Labels: 🐞BugFix

#151 feat : 학부모에게 입금안내 알림톡 연동
  api/src/main/java/com/yedu/backend/domain/matching/application/usecase/MatchingTimetableUseCase.java
  api/src/main/java/com/yedu/backend/domain/matching/domain/service/MatchingTimetableCommandService.java
  api/src/main/java/com/yedu/backend/global/event/publisher/EventPublisher.java
  shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/application/mapper/BizppurioMapper.java
  shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/application/usecase/BizppurioParentsMessage.java
  shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/event/listener/BizppurioParentsMessageListener.java
  shared/common/src/main/java/com/yedu/common/event/bizppurio/PayNotificationEvent.java
Labels: ✨ Feature

#154 feat : 알림톡 연동 마무리
  api/src/main/java/com/yedu/backend/admin/application/usecase/AdminManageUseCase.java
  api/src/main/java/com/yedu/backend/admin/presentation/AdminTestController.java
  api/src/main/java/com/yedu/backend/domain/matching/application/usecase/ClassScheduleMatchingUseCase.java
  api/src/main/java/com/yedu/backend/domain/teacher/application/usecase/TeacherBatchUseCase.java
  api/src/main/java/com/yedu/backend/domain/teacher/application/usecase/TeacherManageUseCase.java
  api/src/main/java/com/yedu/backend/domain/teacher/domain/repository/TeacherDslRepository.java
  api/src/main/java/com/yedu/backend/domain/teacher/domain/repository/TeacherDslRepositoryImpl.java
  api/src/main/java/com/yedu/backend/domain/teacher/domain/service/TeacherGetService.java
  api/src/main/java/com/yedu/backend/domain/teacher/presentation/TeacherBatchController.java
  api/src/main/java/com/yedu/backend/global/event/mapper/BizppurioEventMapper.java
  api/src/main/java/com/yedu/backend/global/event/publisher/EventPublisher.java
  shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/application/mapper/BizppurioMapper.java
  shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/application/usecase/BizppurioTeacherMessage.java
  shared/bizppurio-support/src/main/java/com/yedu/bizppurio/support/event/listener/BizppurioTeacherMessageListener.java
  shared/cache-support/src/main/java/com/yedu/cache/support/storage/MatchingIdApplicationNotifyKeyStorage.java
  shared/cache-support/src/main/java/com/yedu/cache/support/storage/TokenStorage.java
  shared/cache-support/src/main/java/com/yedu/cache/support/storage/UpdateAvailableTimeKeyStorage.java
  shared/common/src/main/java/com/yedu/common/event/bizppurio/TeacherAvailableTimeUpdateRequestEvent.java
  shared/common/src/main/java/com/yedu/common/event/bizppurio/TeacherExchangeEvent.java
  shared/discord-support/src/main/java/com/yedu/discord/support/DiscordWebhookUseCase.java
  shared/discord-support/src/main/java/com/yedu/discord/support/listener/DiscordEventListener.java
Labels: ✨ Feature
